# Generated by Django 5.2 on 2025-04-21 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penarikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('pokok', 'Pokok'), ('wajib', 'Wajib'), ('sukarela', 'Sukarela')], max_length=20)),
                ('jumlah_penarikan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
            ],
        ),
    ]
