# Generated by Django 5.2 on 2025-08-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penarikan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='penarikan',
            table='penarikan',
        ),
    ]
