# Generated by Django 5.2 on 2025-04-21 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjaman', models.DateField()),
                ('kategori', models.CharField(choices=[('harian', 'Harian'), ('bulanan', 'Bulanan'), ('besar', 'Besar')], max_length=20)),
                ('jumlah_pinjaman', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bunga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jatuh_tempo', models.DateField()),
                ('status', models.CharField(default='belum', max_length=10)),
                ('id_anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_bayar', models.DateField()),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_pinjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinjaman.pinjaman')),
            ],
        ),
    ]
