# Generated by Django 5.2.1 on 2025-05-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinjaman',
            name='bunga',
        ),
        migrations.RemoveField(
            model_name='pinjaman',
            name='jumlah_pinjaman',
        ),
        migrations.RemoveField(
            model_name='pinjaman',
            name='kategori',
        ),
        migrations.AddField(
            model_name='pinjaman',
            name='jumlah_barang',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pinjaman',
            name='jumlah_reguler',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pinjaman',
            name='jumlah_usaha',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
