# Generated by Django 5.2 on 2025-05-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0002_remove_pinjaman_bunga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinjaman',
            name='jumlah_bayar',
        ),
    ]
