# Generated by Django 5.2 on 2025-05-19 14:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0003_remove_pinjaman_jumlah_bayar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjaman',
            name='jumlah_cicilan',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Jumlah cicilan pertama', max_digits=12),
        ),
    ]
