# Generated by Django 5.2 on 2025-05-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0004_pinjaman_jumlah_cicilan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinjaman',
            name='jumlah_cicilan',
        ),
    ]
