# Generated by Django 5.2 on 2025-05-19 14:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0006_pinjaman_jumlah_cicilan'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypembayaran',
            name='sisa_pinjaman',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='pinjaman',
            name='sisa_pinjaman',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
