# Generated by Django 5.2.1 on 2025-05-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0007_historypembayaran_sisa_pinjaman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjaman',
            name='status',
            field=models.CharField(default='belum lunas', max_length=15),
        ),
    ]
