# Generated by Django 5.2 on 2025-08-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0008_alter_pinjaman_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypembayaran',
            name='lama_pinjaman',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historypembayaran',
            name='jumlah_bayar',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historypembayaran',
            name='sisa_pinjaman',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
