# Generated by Django 5.2 on 2025-08-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0009_historypembayaran_lama_pinjaman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historypembayaran',
            name='lama_pinjaman',
        ),
        migrations.AddField(
            model_name='pinjaman',
            name='lama_pinjaman',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
