# Generated by Django 5.2 on 2025-08-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0010_remove_historypembayaran_lama_pinjaman_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historypembayaran',
            table='pinjaman_historypembayaran',
        ),
        migrations.AlterModelTable(
            name='pinjaman',
            table='pinjaman_pinjaman',
        ),
    ]
