# Generated by Django 5.2 on 2025-08-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0011_alter_historypembayaran_table_alter_pinjaman_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historypembayaran',
            table='riwayat_pembayaran',
        ),
    ]
