# Generated by Django 5.2 on 2025-08-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0012_alter_historypembayaran_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pinjaman',
            table='pinjaman',
        ),
    ]
