# Generated by Django 5.2 on 2025-04-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_koperasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('bendahara', 'Bendahara'), ('sekretaris', 'Sekretaris'), ('ketua', 'Ketua')], default='ketua', max_length=20),
        ),
    ]
