# Generated by Django 5.2.1 on 2025-05-21 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_koperasi', '0002_alter_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pokok', models.IntegerField()),
                ('jumlah_wajib', models.IntegerField()),
                ('jumlah_sukarela', models.IntegerField()),
                ('id_anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_koperasi.anggota')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryTabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis', models.CharField(max_length=10)),
                ('jumlah', models.IntegerField()),
                ('tabungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historytabungan', to='admin_koperasi.tabungan')),
            ],
        ),
    ]
