# Generated by Django 5.2.1 on 2025-05-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_koperasi', '0003_anggota_tabungan_historytabungan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabungan',
            name='id_anggota',
        ),
        migrations.RemoveField(
            model_name='historytabungan',
            name='tabungan',
        ),
        migrations.DeleteModel(
            name='Anggota',
        ),
        migrations.DeleteModel(
            name='HistoryTabungan',
        ),
        migrations.DeleteModel(
            name='Tabungan',
        ),
    ]
