# Generated by Django 5.2 on 2025-08-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_koperasi', '0004_remove_tabungan_id_anggota_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin_koperasi_admin',
        ),
    ]
