# Generated by Django 5.2 on 2025-08-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_koperasi', '0005_alter_admin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin_koperasi',
        ),
    ]
