# Generated by Django 5.2 on 2025-04-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('jurusan', models.CharField(max_length=50)),
                ('kelas', models.CharField(max_length=20)),
                ('tingkat', models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=10)),
                ('telp', models.CharField(max_length=20)),
                ('tgl_daftar', models.DateField()),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('alasan_keluar', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
