# Generated by Django 5.2 on 2025-04-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota',
            name='alasan_keluar',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='id',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='jurusan',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='nis',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='telp',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='tingkat',
        ),
        migrations.AddField(
            model_name='anggota',
            name='alamat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anggota',
            name='alasan_tidak_aktif',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anggota',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anggota',
            name='id_anggota',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='anggota',
            name='nip',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='anggota',
            name='no_tlp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('tidak aktif', 'Tidak Aktif')], default='aktif', max_length=15),
        ),
    ]
