# Generated by Django 5.2 on 2025-08-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0003_anggota_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterModelTable(
            name='anggota',
            table='anggota_anggota',
        ),
    ]
