# Generated by Django 5.2 on 2025-08-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0004_anggota_password_hash_alter_anggota_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anggota',
            table='anggota',
        ),
    ]
