# Generated by Django 5.2 on 2025-05-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0002_jumlah_sukarela_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabungan',
            name='jumlah_sukarela',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
