# Generated by Django 5.2.1 on 2025-05-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0002_tabungan_jumlah_sukarela'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historytabungan',
            old_name='id_tabungan',
            new_name='tabungan',
        ),
    ]
