# Generated by Django 5.2 on 2025-08-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0003_rename_id_tabungan_historytabungan_tabungan'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historytabungan',
            table='tabungan_historytabungan',
        ),
        migrations.AlterModelTable(
            name='tabungan',
            table='tabungan_tabungan',
        ),
    ]
