# Generated by Django 5.2 on 2025-08-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0004_alter_historytabungan_table_alter_tabungan_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historytabungan',
            table='riwayat_tabungan',
        ),
        migrations.AlterModelTable(
            name='tabungan',
            table='tabungan',
        ),
    ]
