# Generated by Django 5.2 on 2025-04-21 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabungan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiTabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis_transaksi', models.CharField(max_length=20)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.TextField()),
                ('id_tabungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabungan.tabungan')),
            ],
        ),
    ]
