# Generated by Django 5.2.1 on 2025-05-18 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaksitabungan',
            name='id_tabungan',
        ),
        migrations.RemoveField(
            model_name='transaksitabungan',
            name='jenis_transaksi',
        ),
        migrations.AddField(
            model_name='transaksitabungan',
            name='jenis',
            field=models.CharField(choices=[('simpan', 'Simpan'), ('pinjam', 'Pinjam'), ('penarikan', 'Penarikan')], default='simpan', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaksitabungan',
            name='jumlah',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaksitabungan',
            name='keterangan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaksitabungan',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Tabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.PositiveIntegerField(default=0)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaksi.anggota')),
            ],
        ),
        migrations.AddField(
            model_name='transaksitabungan',
            name='tabungan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaksi.tabungan'),
        ),
    ]
