# Generated by Django 5.2.1 on 2025-05-18 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_anggota_remove_transaksitabungan_id_tabungan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksitabungan',
            name='tabungan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaksi.tabungan'),
            preserve_default=False,
        ),
    ]
